[package]
name = "test-transaction-type"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
eyre = "0.6"
dotenvy = "0.15"
ethers = { version = "2", features = ["rustls"] }
